"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['A Quiet Flowerbed.py']
DATA_FILES = ['index.html', 'game.js']
OPTIONS = {'iconfile': '/Users/williamchoi-kim/Desktop/Personal/Coding/flowers/flower.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
